<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15">
  <PropertyGroup>
    <Version>1.0.2.3</Version>
    <Description>Resets the camera direction relative to the world.</Description>
    <PackageProjectUrl>https://github.com/Vueren/ResetCamera</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>
